# Generated by Django 4.2.7 on 2023-12-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MAN', 'Мужчина'), ('WOMAN', 'Женщина')], default='WOMAN', max_length=5, verbose_name='Пол'),
        ),
    ]
