# Generated by Django 4.2.7 on 2023-12-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birthday_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='foto',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MAN', 'Мужчина'), ('WOMAN', 'Женщина')], max_length=5, null=True, verbose_name='Пол'),
        ),
    ]
