version: '3.8'

services:

  db:
    image: postgres:16.1-alpine
    volumes:
    - var/lib/postgres/data
    env_file:
    - ./.env

  cherry_app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  