LOGGER_MAGNIT = {
    'version': 1,
    'formatters': {
        'consoleFormatter': {
            'format': '%(asctime)s - %(name)s - %(levelname)-8s - %(message)s - [* %(filename)s:%(lineno)d *]',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'fileFormatter': {
            'format': '%(asctime)s - %(name)s - %(levelname)-8s - %(message)s - [* %(filename)s:%(lineno)d *]',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'consoleHandler': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG',
            'formatter': 'consoleFormatter',
            'stream': 'ext://sys.stdout',
        },
        'fileHandler': {
            'class': 'logging.handlers.RotatingFileHandler',
            'level': 'INFO',
            'formatter': 'fileFormatter',
            'filename': 'parser_magnit.log',
            'maxBytes': 52428800,
            'backupCount': 3,
        },
    },
    'root': {
        'level': 'DEBUG',
        'handlers': [
            'consoleHandler',
            'fileHandler',
        ],
    },
}

PARSING_MAGNIT = {
    'URL_PRODUCTS': 'https://web-gateway.middle-api.magnit.ru/v1/promotions',
    'URL_CITY': 'https://web-gateway.middle-api.magnit.ru/v1/cities',
    'URL_STORES': 'https://web-gateway.middle-api.magnit.ru/v1/geolocation/store',
    'HEADERS': {
        'Accept': '*/*',
        'Accept-Language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
        'Connection': 'keep-alive',
        'Origin': 'https://magnit.ru',
        'Referer': 'https://magnit.ru/',
        'Sec-Fetch-Dest': 'empty',
        'Sec-Fetch-Mode': 'cors',
        'Sec-Fetch-Site': 'same-site',
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)'
                    'Chrome/119.0.0.0 Safari/537.36',
        'sec-ch-ua': '"Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Linux"',
        'x-app-version': '0.1.0',
        'x-client-name': 'magnit',
        'x-device-id': 'v66jbingss',
        'x-device-platform': 'Web',
        'x-device-tag': 'disabled',
        'x-platform-version': 'window.navigator.userAgent',
    },
    'PARAMS_PRODUCTS': {
        'offset': '0',
        'limit': '1000',
        'storeId': '63452',
        'adult': 'true',
        'sortBy': 'priority',
        'order': 'desc',
    },
    'PARAMS_STORES': {
        'Limit': 3,
        'Radius': 20,
    },
    # Соответствие ключа входных данных с сайта ключу выходных данных
    'KEYS': (
        ('name', 'name'),
        ('barcode', 'barcode'),
        ('category', 'categoryName'),
        ('image_url', 'imageUrl'),
        ('discount_start', 'startDate'),
        ('discount_end', 'endDate'),
        ('discount_rate', 'discountPercentage'),
        ('initial_price', 'oldPrice'),
        ('promo_price', 'price'),
    ),
    # Распределение категорий "Магнит" по категориям приложения
    'CATEGORIES': {
        'PRODUCTS': [
            'Хлеб и выпечка',
            'Овощи и фрукты',
            'Молоко, сыр, яйца',
            'Мясо, птица, колбасы',
            'Замороженные продукты',
            'Напитки',
            'Готовая еда',
            'Чай, кофе, какао',
            'Бакалея, соусы',
            'Кондитерские изделия',
            'Снеки, орехи',
            'Соусы и приправы',
            'Здоровое питание',
            'Рыба и морепродукты',
            'Готовая еда',
        ],
        'CLOTHES': [
            'Одежда и обувь',
        ],
        'HOME': [
            'Дом, сад',
            'Медтовары',
            'Бытовая техника',
            'Бытовая химия',
            'Скидки по карте',
            'Новинки',
            'Досуг',
            'Канцтовары',
            'Витамины и БАД',
            'Аксессуары',
            'Лекарства',
            'Печатная продукция',
        ],
        'COSMETICS': [
            'Косметика и парфюмерия',
            'Гигиена',
        ],
        'KIDS': [
            'Детям',
        ],
        'ZOO': [
            'Зоотовары',
        ],
        'AUTO:': ['Автотовары'],
        'HOLIDAYS': [
            'Алкоголь',
            'Новый год',
        ],
        'DIFFERENT': [
            'Скидки по карте',
            'Скидки на категории',
            '30% бонусами с подпиской',
            'Новинки',
            'Кешбек',
            'Разные категории',
            '0',
            'Проездные. Лотереи',
        ],
    },
    'NO_DATA': -1,
}
