name: develop_deploy

on:
  push:
    branches:
      - feature-actions-deploy

jobs:
  deploy:
    # needs:###
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets. PASSPHRASE }}
        script: |
          cd ~/backend/
          git pull
          git checkout feature-actions-deploy
          touch .env
          echo DB_ENGINE=${{ secrets.DB_ENGINE }} > .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          echo test=test >> .env
          cd ~/infra/
          sudo docker compose stop
          echo log=стоп контейнер >> ../backend/.env
          sudo docker container rm cherry_app
          echo log=удалил контейнер >> ../backend/.env
          sudo docker image rm cherry_app
          echo log=удалил имидж >> ../backend/.env
          sudo docker build -t cherry_app ../backend/
          echo log=создал имидж >> ../backend/.env
          sudo docker compose up -d
          echo log=запустил контейнеры >> ../backend/.env
          sudo docker exec -it cherry_app python manage.py makemigrations
          echo log=создал миграции >> ../backend/.env
          sudo docker exec -it cherry_app python manage.py migrate
          echo log=запустил миграции >> ../backend/.env
          sudo docker exec -it cherry_app python manage.py collectstatic --no-input
          echo log=конец скрипта >> ../backend/.env

