name: develop_deploy

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    # needs:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets. PASSPHRASE }}
        scripts: |
          sudo docker compose stop
          sudo docker container rm cherry_app
          cd ~/backend/
          git checkout develop
          git pull
          touch .env
          echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          sudo docker image rm cherry_app
          sudo docker build -t cherry_app .
          cd ../
          sudo docker compose up -d
          sudo docker exec -it cherry_app bash
          python manage.py makemigrations
          python manage.py migrate
          python manage.py collectstatic --no-input
          exit


