# Generated by Django 4.2.7 on 2023-11-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discount",
            options={
                "ordering": ("discount_rate",),
                "verbose_name": "Скидка",
                "verbose_name_plural": "Скидки",
            },
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_end",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_start",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_unit",
            field=models.CharField(
                choices=[("RUB", "Скидка в рублях"), ("%", "Скидка в процентах")],
                default="%",
                max_length=11,
                verbose_name="Единица измерения",
            ),
        ),
    ]
