# Generated by Django 4.2.7 on 2023-12-13 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение товар', 'verbose_name_plural': 'Изображения товара'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='additional_photo',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='main_image',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Главное изображение продукта'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='q', unique=True, upload_to='product_images/', verbose_name='Дополнительное изображение товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Фото товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
