# Generated by Django 4.2.7 on 2024-01-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Приоритет категории в дизайн-макете'),
        ),
    ]
