# Generated by Django 4.2.7 on 2024-03-04 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='discount',
            name='unique_discount',
        ),
    ]
