# Generated by Django 4.2.7 on 2023-12-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('PRODUCTS', 'Продукты'), ('CLOTHES', 'Одежда и обувь'), ('HOME', 'Для дома и сада'), ('COSMETICS', 'Косметика и гигиена'), ('KIDS', 'Для детей'), ('ZOO', 'Зоотовары'), ('AUTO', 'Авто'), ('HOLIDAYS', 'К празднику'), ('DIFFERENT', 'Разное')], default='PRODUCTS', max_length=9, verbose_name='Название'),
        ),
    ]
