# Generated by Django 4.2.7 on 2023-12-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinstore',
            name='initial_price',
            field=models.CharField(max_length=10, verbose_name='Цена товара без акции'),
        ),
        migrations.AlterField(
            model_name='productsinstore',
            name='promo_price',
            field=models.CharField(max_length=10, verbose_name='Цена товара по акции'),
        ),
    ]
