# Generated by Django 4.2.7 on 2023-11-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount_end',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount_rating',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount_start',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount_unit',
        ),
    ]
