# Generated by Django 4.2.7 on 2024-01-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productsinstore_initial_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='id_in_chain_store',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='id магазина в сети'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Долгата'),
        ),
        migrations.AddConstraint(
            model_name='productsinstore',
            constraint=models.UniqueConstraint(fields=('product', 'store'), name='unique_product_store'),
        ),
    ]
