# Generated by Django 4.2.7 on 2024-01-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_store_id_in_chain_store_storelocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storelocation',
            name='latitude',
            field=models.CharField(default='', max_length=100, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='longitude',
            field=models.CharField(default='', max_length=100, verbose_name='Долгата'),
            preserve_default=False,
        ),
    ]
